### ISSUE TITLE
Designing Login/Landing Page

### ISSUE THREAD

**Issue by studybuddydeveloper** [studybuddydeveloper/StudyBuddyApp#1]
### Landing Page
- [X] Users can create an account @Cakanaga @EUmoye 
> User can create account and saved to firebase. Implemented design @
- [x ] Works on the frontend, designing the sign up and login forms respectively @EUmoye  
> > - [x] Must include full name I.E. First and Last Name @EUmoye  
> > - [x] email address must have a .edu domain @EUmoye  
- [ x] User can sign up a new account @EUmoye 
> > - [ ] email address must be verifiable via email once account is created @EUmoye 
> > - [x] Password includes at least 8 chars including digit, special char, cap char.(firebase default is 6 so need to change that) @EUmoye #TODO
> > - [x]  Account shows up firestore(Firebase Cloud database) @EUmoye 
- [ ] User is able to reset password @EUmoye 
- [x] 4 carousels show for first time users to describe the app and its core functions @EUmoye   
- [x] ~~Unit testing: details found in doc @Cakanaga~~ Will not be implemented in this feature

**Comment by studybuddydeveloper** [comment]
So far, most of the tasks on this sprint have been completed.  @EUmoye worked on the frontend/backend for the login and signup functionality. Two new branches were created to modularize the separate logic for these changes. Once validated and tested, I shall merge both frontend and backend.

**Comment by EUmoye** [comment]
Here's a list of tasks that are still pending in this issue
 - [ ] email address must be verifiable via email once the account is created @EUmoye
 - [ ] User is able to reset password @EUmoye
 - [ ] The user is able to sign up with valid passwords
 - [ ] The user can login with existing credentials @EUmoye
